server:
  port: 8081
spring:
  application:
    name: news-service
  cloud:
    nacos:
      server-addr: localhost:8848
springdoc:
#  api-docs:
#    enabled: true
  packages-to-scan: com.example.joyread.news.controller
