server:
  port: 8081
spring:
  application:
    name: news-service
  cloud:
    nacos:
      server-addr: localhost:8848
  data:
    mongodb:
      host: localhost
      port: 27017
      database: news
      username: mongoadmin
      password: mongoadmin
      authentication-database: admin
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: news
springdoc:
#  api-docs:
#    enabled: true
  packages-to-scan: com.example.joyread.news.controller
