server:
  port: 8084
spring:
  application:
    name: assistant-service
  cloud:
    nacos:
      server-addr: localhost:8848
  ai:
    Base-URL: http://localhost/v1
    API-Key: app-************************
springdoc:
#  api-docs:
#    enabled: true
  packages-to-scan: com.example.joyread.assistant.controller
