server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: docs_news
          uri: lb://news-service
          predicates:
            - Path=/news/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: docs_user
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: docs_search
          uri: lb://search-service
          predicates:
            - Path=/search/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: docs_assistant
          uri: lb://assistant-service
          predicates:
            - Path=/assistant/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: img
          uri: http://localhost:9000
          predicates:
            - Path=/images/**
          filters:
            - StripPrefix=1
        - id: news
          uri: lb://news-service
          predicates:
            - Path=/news/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: search
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: assistant
          uri: lb://assistant-service
          predicates:
            - Path=/assistant/**
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOriginPatterns: "*"
#            allowedMethods:
#              - "GET"
#              - "POST"
#              - "PUT"
#              - "PATCH"
#              - "DELETE"
#              - "OPTIONS"
#            allowedHeaders: "*"
#            allowedCredentials: true
#            maxAge: 360000
springdoc:
#  api-docs:
#    enabled: true
  swagger-ui:
#    enabled: true
    urls:
      - name: news-service
        url: /news/v3/api-docs
      - name: user-service
        url: /users/v3/api-docs
      - name: search-service
        url: /search/v3/api-docs
      - name: assistant-service
        url: /assistant/v3/api-docs
